#!/usr/bin/env bash

pre=:
post=:
printf "$pre%s$post\n" "$@"

##Quoting

#./sa \ this "is a" 'demonstration of' \ quotes\ and\ escapes
# ./sa "a double-quoted single quote, '" "a double-quoted double quote, \""
# ./sa "First argument "'still the first argument'
# echo $'\'line1\'\n\'line2\''

## Brace expansion

# ./sa {one,two,three}
# ./sa {1..3}
# ./sa {a..c}
# ./sa pre{d,l}ate
# ./sa {{1..3},{a..c}}
# ./sa {1..3}{a..c}
# ./sa {01..13..3} 
# ./sa {a..h..3}

## Tilde expansion
# ./sa ~root ~daruch ->not working

## Parameter and Variable Expansion
# ./sa "$var"
# ./sa "${var}"
# ./sa "$first_$last" "${first}_$last"

## Arithmetic Expansion
# ./sa "$(( 1+ 12 ))"
# ./sa "$((13%5))"

## Command substitution
# ./sa "$( date +%Y-%m-%d )"

## Word Splitting
# var="this is a multi-word value"
# ./sa $var "$var"


# var=' spaced
# out '
# sa $var
# :spaced:
# :out:

# IFS=' :'
# var="qwerty  : uiop :: er "
# ./sa $var

## Pathname expansion
./sa f*

## Process substitution

# while read perms links owner group size month day time file
#  do
#  printf "%10d %s\n" "$size" "$file"
#  totalsize=$(( ${totalsize:=0} + ${size:-0} ))
#  done < <(ls -l *)