#!/usr/bin/env bash

_repeat()
{
#@ USAGE: _repeat string number
_REPEAT=$1
while (( ${#_REPEAT} < $2 )) ## Loop until string exceeds desired length
do
_REPEAT=$_REPEAT$_REPEAT$_REPEAT ## 3 seems to be the optimum number
done
_REPEAT=${_REPEAT:0:$2} ## Trim to desired length
}
repeat()
{
_repeat "$@"
printf "%s\n" "$_REPEAT"
}
repeat Do 89