#!/usr/bin/env bash

isvalidip()
{
    case $1 in
      "" | *[!0-9.]* | *[!0-9]) return 1 ;;
    esac

    local IFS=.

    set -- $1

}


for ip in 127.0.0.1 168.260.0.234 1.2.3.4 123.1OO.34.21 204.225.122.150
 do
 if isvalidip "$ip"
 then
 printf "%15s: valid\n" "$ip"
 else
 printf "%15s: invalid\n" "$ip"
 fi
 done