#!/bin/bash

#: Title: Set Parameters via Menu
#: Synopsis: menus
#: Date: 4/19/2023
#: Version: 1.0
#: Author: daruh
#: Options: -

while : ; do
  printf "\n\n%s\n" "$bar"
  printf " Dictionary parameters\n"
  printf "%s\n\n" "$bar"
  printf " 1. Directory containing dictionary: %s\n" "$dict"
  printf " 2. File containing word list: %s\n" "$wordfile"
  printf " 3. File containing compound words and phrases: %s\n" "$compoundfile"
  printf " 4. Include compound words and phrases in results? %s\n" "$compounds"
  printf " q. %s\n" "Exit menu"
  printf "\n%s\n\n" "$bar"

  ## get user response
  read -sn1 -p "Select (1,2,3,4,q): " input
  echo
  ## interpret user response

  case $input in
  1) read -ep "Enter dictionary directory: " dict ;;
  2) read -ep "Enter word-list file: " wordfile ;;
  3) read -ep "Enter compound-word file: " compoundfile ;;
  4) [ "$compounds" = y ] && compounds=n || compounds=y ;;
  q) break ;;
  *) printf "\n\aInvalid selection: %c\n" "$input" >&2
  sleep 2
  ;;
  esac
done

