#!/bin/bash

#: Title: Print Result of Arithmetic Expression
#: Synopsis: calc
#: Date:
#: Version: 1.0
#: Author: daruh
#: Options: -

calc() {
  local result=$(awk 'BEGIN { OFMT="%f"; print '"$*"'; exit}')
  case $result in
  *.*0) result=${result%"${result##*[!0]}"} ;;
  esac
  printf "%s\n" "$result"
}
