#!/bin/bash

#: Title: Change directory, storing new directory on DIRSTACK
#: Synopsis: cdf
#: Date: 19/04/2023
#: Version: 1.0
#: Author: daruh
#: Options:

cdf() {
  local dir error ##vars
  while :; do
    case $1 in
    --) break ;;
    -*) shift ;;
    *) break ;;
    esac
  done

  dir $1

  if [[ -n "$dir" ]]; then
    pushd "$dir"
  else
    pushd "$HOME"
  fi >/dev/null

  error=$?

  if [[ $error -ne 0 ]]; then
    builtin cd "$dir"
  fi
  return "$error"

} >/dev/null
